### ISSUE TITLE
client todo

### ISSUE THREAD

**Issue by brandonbrown** [brandonbrown/emademos#1]
Marketing:
- [ ] Homepage
- [ ] Support pages
  - [ ] TBD

User:
- [ ] Log In
- [ ] Register
- [ ] Registration Processes (forgot email/pw)
- [ ] Empty States
- [ ] Subscriptions View
- [ ] Band Feed View
- [ ] Profile Information and Fields
- [ ] Payment Info
- [ ] Settings Information and Fields
- [ ] Help
